### ISSUE TITLE
Frage "Erforderliches Update verfügbar" während einer Kampangne

### ISSUE THREAD

**Issue by vjuergens** [fabianbees/breitbandmessung-docker#15]
Hallo,

ich habe eine Kampangne angefangen und diese blieb stehen. Wenn ich auf "Messung durchführen" klicke kommt die oben genannte Meldung. Wo kann ich die APP austauschen. Ein erneutes Ausrollen des Container hat keine Besserung gebracht.

Vielen Dank für Deine Mühen

Volkmar

**Comment by fabianbees** [comment]
Bin aktuell im Urlaub und kann mir das ganze erst später anschauen.

Es wäre möglich, dass Sie die **appdaten** also bspw. `./breitbandmessung/data` auf dem Host nicht gelöscht haben, bevor Sie den Container neu angelegt haben.

**Comment by vjuergens** [comment]
Bei der Installation als Container wird die Version 3.4.0-698 geladen, bei einer Kontrollinstallation auf einem Ubuntu wird 3.5.0 heruntergeladen. Ist die Version oder der Downloadserver irgendwo hinterlegt?

Gruß Volkmar

[cont-init   ] 50-install-latest-breitbandmessung.sh: 2023-10-18 17:56:31 (4.47 MB/s) - 'Breitbandmessung-3.4.0-linux.deb' saved [73821320/73821320]
[cont-init   ] 50-install-latest-breitbandmessung.sh: 
[cont-init   ] 50-install-latest-breitbandmessung.sh: Breitbandmessung-3.4.0-linux.deb: OK
[cont-init   ] 50-install-latest-breitbandmessung.sh: Checksum matches, installing ...
[cont-init   ] 50-install-latest-breitbandmessung.sh: Selecting previously unselected package breitbandmessung.
[cont-init   ] 50-install-latest-breitbandmessung.sh: (Reading database ... 25899 files and directories currently installed.)
[cont-init   ] 50-install-latest-breitbandmessung.sh: Preparing to unpack Breitbandmessung-3.4.0-linux.deb ...
[cont-init   ] 50-install-latest-breitbandmessung.sh: Unpacking breitbandmessung (3.4.0-698) ...
[cont-init   ] 50-install-latest-breitbandmessung.sh: Setting up breitbandmessung (3.4.0-698) ...

**Comment by fabianbees** [comment]
Okay, verstehe. Ich sehe gerade dass gestern ein Update auf 3.5.0 herausgegeben wurde.

Ich werde in ca. zwei Wochen nach meinem Urlaub ein Update für den Container rausbringen, dadurch sollte das Problem gelöst werden.

**Comment by vjuergens** [comment]
Hallo,

ich werde mich in Geduld üben und wünsche noch einen schönen Resturlaub.

Gruß Volkmar

------ Originalnachricht ------
Von "fabianbees" ***@***.***>
An "fabianbees/breitbandmessung-docker" 
***@***.***>
Cc "vjuergens" ***@***.***>; "Author" ***@***.***>
Datum 18.10.2023 18:19:42
Betreff Re: [fabianbees/breitbandmessung-docker] Frage "Erforderliches 
Update verfügbar" während einer Kampangne (Issue #15)

**Comment by fabianbees** [comment]
Bitte nochmal mit der neusten Version testen, ich habe eben die Version `3.5.0` veröffentlicht. Der Build des neuen Image ist soeben fertig geworden. Notfalls einmal mit `docker pull <imagename>` das neue Image pullen.

Grüße, Fabian

**Comment by vjuergens** [comment]
Hallo,

es wird jetzt die aktuelle App geladen. Danke für den Einsatz

cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           Breitbandmessung                              │
    │ Application Version:   3.5.0                                         │
    │ Docker Image Version:  n/a                                           │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
