### ISSUE TITLE
"Erforderliches Update verfügbar"

### ISSUE THREAD

**Issue by phrxmd** [fabianbees/breitbandmessung-docker#19]
On a fresh install from Github, the app complains that a necessary update is available and won't do any measurements:

![grafik](https://github.com/fabianbees/breitbandmessung-docker/assets/35058059/c863e97d-489a-4ae9-b0cb-fbf253dac60d)

What's the best way to regenerate the container with the latest app?

**Comment by phrxmd** [comment]
OK, I think I worked it out, should be addressed in #20

**Comment by fabianbees** [comment]
I have already setup automation for updating of new versions, threfor it is not necessary to submit PR just for updating.
The CI Pipeline runs every 3 days and checks for new releases.

I have triggered my pipeline now manually, so this can be closed.
