### ISSUE TITLE
In Portainer kein Pull möglich

### ISSUE THREAD

**Issue by ados1989** [fabianbees/breitbandmessung-docker#2]
Hallo ich bekomme immer die Fehlermeldung:

failed to deploy a stack: breitband-desktop Pulling breitband-desktop Error Error response from daemon: pull access denied for breitband, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

kannst du mir bitte weiter helfen?

Gruß

**Comment by fabianbees** [comment]
Bitte Dokumentation durchlesen!

Das Image ist nicht auf Docker-Hub veröffentlicht, daher Pull nicht möglich.

Das Image muss lokal gebaut werden, siehe:
https://github.com/fabianbees/breitbandmessung-docker#building-the-container
