### ISSUE TITLE
Bestätigungsscreen blockiert die Messung

### ISSUE THREAD

**Issue by eld0rad0x** [fabianbees/breitbandmessung-docker#22]
Hallo,

ich habe heute den Container nach Anleitung eingerichtet. Gestern funktionierte die Automatisierung unter einem anderem Setup noch. Heute in einem frischen Setup bekomme ich nun den im Screenshot zu sehenden Dialog, in dem man vor jeder Messung zuvor 6 Kästchen ankreuzen muss bevor die Messung startet. Kann man dies in die Automatisierung mit aufnehmen?

Vielen Dank für deine großartige Arbeit!

![Breitbandmessung](https://github.com/fabianbees/breitbandmessung-docker/assets/145979309/51808d83-8fe4-4875-b310-e7969a81822e)

**Comment by fabianbees** [comment]
Bei mir funktioniert die Automatisierung auch mit der neusten Version problemlos. Also auch das anklicken der Kästchen.
Evtl. mal den Docker-Container neu starten, oder neu erstellen.

Den Fehler, dass die Kästchen nicht geklickt werden kann ich nicht reproduzieren.

**Comment by eld0rad0x** [comment]
Ok, ich hab den Container nun neuinstalliert und es geht wieder. Top danke dir :)

Evtl. hat er sich auch daran gestört, dass ich die Websession im Hintergrund noch offen hatte und er dort den Cursor nicht sauber setzen konnte beim anklicken der Kästchen. Ich hab die Session beendet und den Container neuinstalliert und 1 bis 2 Minuten gewartet. Da lief der erste Test beim prüfen bereits durch.
