### ISSUE TITLE
[✅Solved] Deployment error on ARM-Architecture (➡️ includes Raspberry Pi's)

### ISSUE THREAD

**Issue by DJ-Dan** [fabianbees/breitbandmessung-docker#4]
Hello everyone,

I have two Portainers running and I get the following error message on both when creating stacks:

`failed to deploy a stack: breitband-desktop Pulling breitband-desktop Warning failed to solve: executor failed running [/bin/sh -c apt update && apt upgrade -yy && apt install -y apt-utils nano htop libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm-dev libxss1 libasound2 wget xterm libnss3 locales xdotool xclip && wget https://download.breitbandmessung.de/bbm/Breitbandmessung-linux.deb && dpkg -i Breitbandmessung-linux.deb && locale-gen de_DE.UTF-8 && rm -rf /var/cache/apt /var/lib/apt/lists]: exit code: 1`

I proceeded as described in the picture here in GitHub or as described in the video from SemperVideo.
Is anyone able to help me?

**Comment by nicks-technik** [comment]
I get the same error

**Comment by fabianbees** [comment]
I cannot reproduce this error on my system.

Have you tried any other deployment options (for example via docker compose) as described in the Reademe.md?

**Comment by goldjunge91** [comment]
> 

are u running it on a raspberry pi? then its not working

**Comment by DJ-Dan** [comment]
> > 
> 
> are u running it on a raspberry pi? then its not working

Yes, why doesn't it run on a raspberry pi?

**Comment by goldjunge91** [comment]
> 

I do not know. but i test it, with my rpi4 with standard setup don't work. then with fresh installation Don't work. all iso was the 64bit version
Ubuntu + Docker on my Laptop, It Work
Windows 10 & 11 + Docker, it Work

**Comment by fabianbees** [comment]
see also https://github.com/fabianbees/breitbandmessung-docker#support-for-arm-architecture-raspberry-pi

The ARM-Architecture (➡️ also all Raspberry Pi's)  is not supported!

Support for this architecture cannot be provided, as the precompiled binary of the "breitbandmessung.de" program is not available for this architecture.

**Comment by xXFreeFunXx** [comment]
I sent a letter to the developers and received the following reply (in German):

**Response from 10.12.2024**
```
Sehr geehrter Herr FreeFun,

vielen Dank für Ihren Hinweis.

Bei der Entwicklung der Breitbandmessung Desktop-App wurde entschieden, grundsätzlich die drei Betriebssysteme Windows, macOS und Linux zu unterstützen.
Dabei sollen die aktuellen und marktführenden Versionen von Microsoft Windows (Windows 10 und 11) und Apple macOS (ab macOS 10.15) und innerhalb von Linux Debian/Ubuntu-Derivate unterstützt werden.

Da die Desktop-App als Nachweisverfahren für eine Minderung eingesetzt wird, muss diese für eine bestimmte Betriebssystem-Version neben geeigneten Implementierungen zur Erkennung der technischen Voraussetzungen auch auf die messtechnischen Unterschiede analysiert, implementiert und getestet werden.
Eine Überprüfung ist sowohl bei betriebssystemseitigen, als auch bei softwareseitigen Updates der Breitbandmessung nötig. Aufgrund des hierfür notwendigen Aufwandes findet eine Anpassung nur auf die oben genannten Systeme statt.

Aktuell ist nicht angedacht, die Breitbandmessung für weiter Varianten von Linux wie z.B. openSuse oder Arch Linux oder Windows anzubieten.

Mit freundlichen Grüßen

Ihr Breitbandmessung.de Team

[info@breitbandmessung.de](mailto:info@breitbandmessung.de)
[www.breitbandmessung.de](http://www.breitbandmessung.de/)

Die handelsrechtlichen Pflichtangaben finden Sie unter Impressum auf https://breitbandmessung.de/impressum
```
