### ISSUE TITLE
Can't export/download Reports

### ISSUE THREAD

**Issue by JamDaBam** [fabianbees/breitbandmessung-docker#5]
Apparently the container doesn't have any permission to save the reportfiles.
Neither the default directory which popups if you click on the save button or the home directory have permissions to save the files.

Only the tmp directory worked for me but i can't mount it out because on the container startup script it want to clean the tmp folder and then it stuck.

<img src="https://github.com/fabianbees/breitbandmessung-docker/assets/46002896/5af0ca21-0f7e-43d0-8ed8-c1cd491ec958" data-canonical-src="https://github.com/fabianbees/breitbandmessung-docker/assets/46002896/5af0ca21-0f7e-43d0-8ed8-c1cd491ec958" width="400" height="150" />

Do you know if there is a way to export the files?

**Comment by LizenzFass78851** [comment]
Try to save the file in the directory `/config/xdg/config/Breitbandmessung` because the directory is mounted as volume by default (if deployed according to the instructions)

**Comment by JamDaBam** [comment]
Oh sry my bad.
This was the easiest solution.

Thank you.
