### ISSUE TITLE
Update der Desktop-App

### ISSUE THREAD

**Issue by RPiList** [fabianbees/breitbandmessung-docker#7]
Hi,
offenbar hat die offizielle App ein Update erhalten.

Die App im Docker-Container prüft vor jedem Test auf Update und bricht damit das Skript des Containers die Tests automatisch durchlaufen zu lassen.
![Unbenannt](https://github.com/fabianbees/breitbandmessung-docker/assets/56664851/b0d37760-9fb6-4d0a-a488-0a106fce5c53)

Viele Grüße

**Comment by LizenzFass78851** [comment]
Ich habe das bei mir getestet, eine Einzelmessung oder weitere Messungen sind somit ohne hin nur dann möglich, wenn die Breitbandmessung App nach Erscheinen der Meldung, dass es ein Update braucht, aktualisiert wird.
![Screenshot (85)](https://github.com/fabianbees/breitbandmessung-docker/assets/82592556/49187a39-1f08-49f7-8c80-aa87ee37bf6d)
Wie im Bild zusehen, steht bei mir "erforderliches Update verfügbar" und die Schaltfläche "Einzelmessung starten" ist ausgegraut.
Ja, es ist auch, wenn man die "Messkampagne" starten möchte, so.

-----

Das Updaten des Containers inkl. der Breitbandmessung App funktioniert am besten, in dem man das Containerimage neu baut.
- Bei docker-compose in den Verzeichniss in den die `Dockerfile` und `docker-compose.yml` liegt:
`docker-compose build && docker-compose down && docker-compose up -d`
- (Wenn sie das aktuelle Dockerfile aus dem Repository verwenden)

**Comment by fabianbees** [comment]
> Ich habe das bei mir getestet, eine Einzelmessung oder weitere Messungen sind somit ohne hin nur dann möglich, wenn die Breitbandmessung App nach Erscheinen der Meldung, dass es ein Update braucht, aktualisiert wird.

Exakt! Dem kann ich nur zustimmen.
(Dies wird von der Breitbandmessung-App selbst so vorgegeben, dass Messungen immer nur mit der aktuellsten Version durchgeführt werden können.)

Das Containerimage muss lokal neu gebaut werden, anschließend muss der Container neu erstellt werden.
Danach sind Messungen mit der neueren Version wieder möglich.
