### ISSUE TITLE
Deployment Error in Portainer

### ISSUE THREAD

**Issue by Kiter1988** [fabianbees/breitbandmessung-docker#8]
When I try to deploy the stack with this yaml, it causes an error. Is my stack incorrect ?

`failed to deploy a stack: breitband-desktop Pulling breitband-desktop Warning failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: failed to init repo at /volume1/@docker/btrfs/subvolumes/5wm0boe85p0hww22djs1lk2x4: exec: "git": executable file not found in $PATH`

Thats my Stack

`version: "3.8"
services:
  breitband-desktop:
    image: breitband:latest
    build: https://github.com/fabianbees/breitbandmessung-docker.git
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
      - 5800:5800
    restart: unless-stopped`

**Comment by LizenzFass78851** [comment]
Try installing `git` on the Docker machine/VM.

 - For Debian / Ubuntu
 `apt install git -y`

 Maybe with a bit of luck it was because of that.

**Comment by fabianbees** [comment]
Closing issue after inactivity.

Feel free to reropen issue after providing additional information on how to reproduce this issue.
